version: "3.9"
services:

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: crud
      MYSQL_USER: aimpree
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mynetwork

  api:
    build: .
    ports:
      - "500:500"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: aimpree
      DB_PASSWORD: 1234
      DB_DATABASE: crud
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge